version: "3"
services:
  web:
    image: canals/php
    container_name: web
    ports:
      - "5580:80"
      - "5543:443"
    volumes :
      - ./web:/var/www/html
      - ./src:/var/www/src
    links :
      - mysql:db

  mysql:
    image: mysql:5.6
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - "3603:3306"

  adminer:
     image: adminer
     ports:
       - "8080:8080"
     links:
       - mysql:db
