version: "3"

networks:
  local_network:
    driver: bridge

services:
  php:
    image: canals/php:7.1-cli
    expose:
      - "8000"
    ports:
      - "8800:8000"
    volumes:
     - ./:/var/php
    working_dir: /var/php
    networks:
      - local_network
    command: php -S 0.0.0.0:8000 web/index-cli.php
    links :
      - mysql:db
      - mongo:mongo
#      - mail:mail
#      - postgres:pg

#############################
# mysql + adminer / can be replaced by mariadb
#############################
  mysql:
#    image: mysql:5.6
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root66
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_DATABASE=mydatab
    networks:
      - local_network
    ports:
      - "3603:3306"
    volumes :
      - ./sql:/var/sql

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - local_network
    links:
      - mysql:db



##############################################
# A second php service
##############################################

#  api:
#      image: canals/php
#      container_name: api
##      environment:
#       - VHOST_HOSTNAME=api.local
#       - VHOST_DOCROOT=/var/www/api
#     ports:
#       - "6080:80"
#       - "6443:443"
#     volumes :
#       - ./api:/var/www/api
#       - ./src:/var/www/src
#       - ./html:/var/www/html
#     networks:
#       - local_network
#     links :
#        - mysql:db

##################################
# postgres + adminer
###################################
# postgres:
#   image: postgres
#   container_name: postgres.local
#   environment :
#     - POSTGRES_PASSWORD = pgroot
#     - POSTGRES_USER = pguser
#   networks:
#     - local_network
#   ports:
#     - "5432:5432"

# adminer-pg:
#   image: adminer
#   container_name: adminer_pg.dev.local
#   networks:
#     - local_network
#   ports:
#     - "8088:8080"
#   links:
#     - postgres:db
#

################################################
# mongodb & mongo-express
###############################################
  mongo:
    image: mongo:3.4
    networks:
      - local_network
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    networks:
      - local_network
    ports:
      - "8081:8081"
    links:
      - mongo:mongo

##############################################
# mailcatcher
##############################################
## mail:
#    image: schickling/mailcatcher
#    container_name: mail.dev.local
#    networks:
#       - local_network
#    ports:
#      - "1080:1080"

########################################
# shared storage : useful for, e.g. sharing
#   uploaded documents (img, others) between multiple services
########################################
volumes:
   data: