version: "3"
services:
  web:
    image: canals/php
    container_name: web_test
    environment:
      - VHOST_HOSTNAME=web.test.local
      - VHOST_DOCROOT=/var/www/web
    ports:
      - "5080:80"
      - "5543:443"
    volumes :
      - ./web:/var/www/web
      - ./src:/var/www/src
      - ./html:/var/www/html
      - data:/var/www/data
    links :
      - mysql:db
      - postgres:pg
      - mongo:mongo
      - mail:mail

#############################
# mysql + adminer / can be replaced by mariadb
#############################
 mysql:
   image: mysql:5.6
   image: mariadb:latest
   container_name: mysql_test
   environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=user
     - MYSQL_PASSWORD=user
   ports:
     - "3603:3306"

 adminer:
    image: adminer
    ports:
      - "8080:8080"
    links:
      - mysql:db

##################################
# postgres + adminer
###################################
  postgres:
    image: postgres
    container_name: postgres_test
    environment :
      - POSTGRES_PASSWORD = pgroot
      - POSTGRES_USER = pguser
    ports:
      - "5432:5432"

  adminer-pg:
    image: adminer
    container_name: adminer_pg_test
    ports:
      - "8088:8080"
    links:
      - postgres:db


##############################################
# A second php service
##############################################

#  api:
#      image: canals/php
#      container_name: api
##      environment:
#       - VHOST_HOSTNAME=api.local
#       - VHOST_DOCROOT=/var/www/api
#     ports:
#       - "6080:80"
#       - "6443:443"
#     volumes :
#       - ./api:/var/www/api
#       - ./src:/var/www/src
#       - ./html:/var/www/html
#     links :
#        - mysql:db

################################################
# mongodb & mongo-express
###############################################
   mongo:
     image: mongo:3.4
     container_name: mongo_test
     ports:
         - 27017:27017

   mongo-express:
        image: mongo-express:latest
        container_name: mongo_express_test
        ports:
          - "8081:8081"#
        links:
          - mongo:mongo

##############################################
# mailcatcher
##############################################
  mail:
     image: schickling/mailcatcher
     container_name: mail_test
     ports:#
       - "1080:1080"

########################################
# shared storage : useful for, e.g. sharing
#   uploaded documents (img, others) between multiple services
########################################
volumes:
   data: